### PR TITLE
added windows support ,  path, virtual environment  , fixed multiple session/db creation 

### PR DESCRIPTION
**Pull request by codewarnab**
```new file:   run.bat
         README.md
	modified:   run.sh
	modified:   src/db.py
	modified:   src/telegram.py
```

### CODE REVIEW

**Comment by FujiwaraChoki** [comment]
Please remove `neon_db` and `cloud_db` altogether as previously stated. I don't know what that is and not planning to keep that in, other than that, this PR seems great!

**Comment by codewarnab** [comment]
> Please remove `neon_db` and `cloud_db` altogether as previously stated. I don't know what that is and not planning to keep that in, other than that, this PR seems great!

i have already removed that neon db in this pr [ check the fix branch on my repo ](https://github.com/codewarnab/TeleSync/tree/fix)

**Comment by FujiwaraChoki** [comment]
Alright, have you tested whether it works? Also, could you fix some grammar mistakes in the README?

**Comment by codewarnab** [comment]
> Alright, have you tested whether it works? Also, could you fix some grammar mistakes in the README?

yes i have tested it properly . i am unable to spot any grammer mistakes in README can you please comment on those lines with grammar mistakes or you can edit them **i have allowed edit fom maintainer option**

**Comment by FujiwaraChoki** [comment]
Great! Will merge now. Thanks for you hard work! :)

**Pull request merged**
